### ISSUE TITLE
Building for Allegro 5.0.11 on OS X

### ISSUE THREAD

**Issue by kalouantonis** [dleslie/allegro-egg#10]
Hi again, 

I'm still having issues on OS X with allegro 5.0.11. It seems like its attempting to bind to d3d functionality, which is obviously not existent. 

Here's the error log. 

```
allegro.c:2594:38: warning: passing 'unsigned char *' to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
C_r=C_int_to_num(&C_a,al_utf8_encode(t0,t1));
                                     ^~
/usr/local/include/allegro5/utf8.h:135:39: note: passing argument to parameter 's' here
AL_FUNC(size_t, al_utf8_encode, (char s[], int32_t c));
                                      ^
/usr/local/include/allegro5/internal/alconfig.h:172:62: note: expanded from macro 'AL_FUNC'
   #define AL_FUNC(type, name, args)               type name args
                                                             ^
allegro.c:3178:22: warning: passing 'unsigned char *' to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
al_ustr_to_buffer(t0,t1,t2);
                     ^~
/usr/local/include/allegro5/utf8.h:33:65: note: passing argument to parameter 'buffer' here
AL_FUNC(void, al_ustr_to_buffer, (const ALLEGRO_USTR *us, char *buffer, int size));
                                                                ^
/usr/local/include/allegro5/internal/alconfig.h:172:62: note: expanded from macro 'AL_FUNC'
   #define AL_FUNC(type, name, args)               type name args
                                                             ^
allegro.c:3203:61: warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
C_r=C_mpointer_or_false(&C_a,(void*)al_ustr_new_from_buffer(t0,t1));
                                                            ^~
/usr/local/include/allegro5/utf8.h:29:63: note: passing argument to parameter 's' here
AL_FUNC(ALLEGRO_USTR *, al_ustr_new_from_buffer, (const char *s, size_t size));
                                                              ^
/usr/local/include/allegro5/internal/alconfig.h:172:62: note: expanded from macro 'AL_FUNC'
   #define AL_FUNC(type, name, args)               type name args
                                                             ^
allegro.c:3362:15: warning: initializing 'ALLEGRO_USTR *' (aka 'struct _al_tagbstring *') with an expression of type 'const ALLEGRO_USTR *' (aka 'const struct _al_tagbstring *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ALLEGRO_USTR *ustr = al_ref_buffer(&info, &txtp[start], end - start);
              ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
allegro.c:3385:15: warning: initializing 'ALLEGRO_USTR *' (aka 'struct _al_tagbstring *') with an expression of type 'const ALLEGRO_USTR *' (aka 'const struct _al_tagbstring *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ALLEGRO_USTR *ustr = al_ref_buffer(&info, text, length);
              ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
allegro.c:3406:15: warning: initializing 'ALLEGRO_USTR *' (aka 'struct _al_tagbstring *') with an expression of type 'const ALLEGRO_USTR *' (aka 'const struct _al_tagbstring *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ALLEGRO_USTR *ustr = al_ref_buffer(&info, text, length);
              ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
allegro.c:3772:1: warning: implicit declaration of function '_al_put_pixel' is invalid in C99 [-Wimplicit-function-declaration]
_al_put_pixel(bmp, x, y, *c);
^
allegro.c:5206:40: warning: passing 'unsigned char *' to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
C_r=C_mpointer(&C_a,(void*)al_fgets(t0,t1,t2));
                                       ^~
/usr/local/include/allegro5/file.h:74:57: note: passing argument to parameter 'p' here
AL_FUNC(char*, al_fgets, (ALLEGRO_FILE *f, char * const p, size_t max));
                                                        ^
/usr/local/include/allegro5/internal/alconfig.h:172:62: note: expanded from macro 'AL_FUNC'
   #define AL_FUNC(type, name, args)               type name args
                                                             ^
allegro.c:6028:32: warning: implicit declaration of function 'al_get_allegro_image_version' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_unsigned_int_to_num(&C_a,al_get_allegro_image_version());
                               ^
allegro.c:6035:1: warning: implicit declaration of function 'al_shutdown_image_addon' is invalid in C99 [-Wimplicit-function-declaration]
al_shutdown_image_addon();
^
allegro.c:6042:15: warning: implicit declaration of function 'al_init_image_addon' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_mk_bool(al_init_image_addon());
              ^
/usr/local/Cellar/chicken/4.9.0.1/include/chicken/chicken.h:1098:38: note: expanded from macro 'C_mk_bool'
#define C_mk_bool(x)               ((x) ? C_SCHEME_TRUE : C_SCHEME_FALSE)
                                     ^
allegro.c:6238:32: warning: implicit declaration of function 'al_get_allegro_physfs_version' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_unsigned_int_to_num(&C_a,al_get_allegro_physfs_version());
                               ^
allegro.c:6245:1: warning: implicit declaration of function 'al_set_physfs_file_interface' is invalid in C99 [-Wimplicit-function-declaration]
al_set_physfs_file_interface();
^
allegro.c:6252:32: warning: implicit declaration of function 'al_get_allegro_memfile_version' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_unsigned_int_to_num(&C_a,al_get_allegro_memfile_version());
                               ^
allegro.c:6265:38: warning: implicit declaration of function 'al_open_memfile' is invalid in C99 [-Wimplicit-function-declaration]
ALLEGRO_FILE *file = (ALLEGRO_FILE *)al_open_memfile(mem, size, mode);
                                     ^
allegro.c:6265:22: warning: cast to 'ALLEGRO_FILE *' (aka 'struct ALLEGRO_FILE *') from smaller integer type 'int' [-Wint-to-pointer-cast]
ALLEGRO_FILE *file = (ALLEGRO_FILE *)al_open_memfile(mem, size, mode);
                     ^
allegro.c:7199:28: warning: implicit declaration of function 'al_get_d3d_device' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_a_double_to_num(&C_a,al_get_d3d_device(t0));
                           ^
/usr/local/Cellar/chicken/4.9.0.1/include/chicken/chicken.h:1368:74: note: expanded from macro 'C_a_double_to_num'
#define C_a_double_to_num(ptr, n)       C_double_to_number(C_flonum(ptr, n))
                                                                         ^
allegro.c:7207:15: warning: implicit declaration of function 'al_is_d3d_device_lost' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_mk_bool(al_is_d3d_device_lost(t0));
              ^
/usr/local/Cellar/chicken/4.9.0.1/include/chicken/chicken.h:1098:38: note: expanded from macro 'C_mk_bool'
#define C_mk_bool(x)               ((x) ? C_SCHEME_TRUE : C_SCHEME_FALSE)
                                     ^
allegro.c:7218:1: warning: implicit declaration of function 'al_get_d3d_texture_position' is invalid in C99 [-Wimplicit-function-declaration]
al_get_d3d_texture_position(bmp, &u, &v);
^
allegro.c:7232:28: warning: implicit declaration of function 'al_get_d3d_video_texture' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_a_double_to_num(&C_a,al_get_d3d_video_texture(t0));
                           ^
/usr/local/Cellar/chicken/4.9.0.1/include/chicken/chicken.h:1368:74: note: expanded from macro 'C_a_double_to_num'
#define C_a_double_to_num(ptr, n)       C_double_to_number(C_flonum(ptr, n))
                                                                         ^
allegro.c:7240:28: warning: implicit declaration of function 'al_get_d3d_system_texture' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_a_double_to_num(&C_a,al_get_d3d_system_texture(t0));
                           ^
/usr/local/Cellar/chicken/4.9.0.1/include/chicken/chicken.h:1368:74: note: expanded from macro 'C_a_double_to_num'
#define C_a_double_to_num(ptr, n)       C_double_to_number(C_flonum(ptr, n))
                                                                         ^
allegro.c:7247:15: warning: implicit declaration of function 'al_have_d3d_non_square_texture_support' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_mk_bool(al_have_d3d_non_square_texture_support());
              ^
/usr/local/Cellar/chicken/4.9.0.1/include/chicken/chicken.h:1098:38: note: expanded from macro 'C_mk_bool'
#define C_mk_bool(x)               ((x) ? C_SCHEME_TRUE : C_SCHEME_FALSE)
                                     ^
allegro.c:7254:15: warning: implicit declaration of function 'al_have_d3d_non_pow2_texture_support' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_mk_bool(al_have_d3d_non_pow2_texture_support());
              ^
/usr/local/Cellar/chicken/4.9.0.1/include/chicken/chicken.h:1098:38: note: expanded from macro 'C_mk_bool'
#define C_mk_bool(x)               ((x) ? C_SCHEME_TRUE : C_SCHEME_FALSE)
                                     ^
23 warnings generated.
Undefined symbols for architecture x86_64:
  "_al_get_d3d_device", referenced from:
      _f_23846 in allegro.o
  "_al_get_d3d_system_texture", referenced from:
      _f_23803 in allegro.o
  "_al_get_d3d_texture_position", referenced from:
      _stub5240 in allegro.o
  "_al_get_d3d_video_texture", referenced from:
      _f_23813 in allegro.o
  "_al_have_d3d_non_pow2_texture_support", referenced from:
      _f_23797 in allegro.o
  "_al_have_d3d_non_square_texture_support", referenced from:
      _f_23800 in allegro.o
  "_al_is_d3d_device_lost", referenced from:
      _f_23836 in allegro.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Error: shell command failed with nonzero exit status 256:

  '/usr/local/Cellar/chicken/4.9.0.1/bin/csc' -feature compiling-extension -setup-mode    -s -d1 allegro.scm -j allegro  -L/usr/local/lib -lallegro  -L/usr/local/lib -lallegro_primitives -lallegro  -L/usr/local/lib -lallegro_color -lallegro  -L/usr/local/lib -lallegro_dialog -lallegro  -L/usr/local/lib -lallegro_main -lallegro  -L/usr/local/lib -lallegro_physfs -lallegro  -L/usr/local/lib -lallegro_font -lallegro  -L/usr/local/lib -lallegro_ttf -lallegro_font -lallegro  -L/usr/local/lib -lallegro_audio -lallegro  -L/usr/local/lib -lallegro_memfile -lallegro  -L/usr/local/lib -lallegro_acodec -lallegro_audio -lallegro  -L/usr/local/lib -lallegro_image -lallegro  -O3 -C -O3 -Dimproved-64-bit-support -Dhas-allegro-primitives -Dhas-allegro-color -Dhas-allegro-dialog -Dhas-allegro-main -Dhas-allegro-physfs -Dhas-allegro-font -Dhas-allegro-ttf -Dhas-allegro-audio -Dhas-allegro-memfile -Dhas-allegro-acodec -Dhas-allegro-image


Error: shell command terminated with nonzero exit code
17920
"'/usr/local/Cellar/chicken/4.9.0.1/bin/csi' -bnq -setup-mode -e \"(require-libr...
``§

**Comment by dleslie** [comment]
Sorry about the delay, I've been on vacation.

I don't actually own a Mac; the OSX support was submitted as a patch by a previous user. 

I see a lot of scary 'implicitly-defined' warnings in there. It reads to me like the linker isn't properly importing or finding the library.

**Comment by kalouantonis** [comment]
I thought that might be the case too, but running `pkg-config --libs allegro-5.0` seemed to work just fine, returning `-L/usr/local/lib -lallegro-5.0`. 

I've also tested the compilation with a simple C program compiled with `gcc simple.c -o simple -L/usr/local/lib -lallegro-5.0`

I don't know what I might be missing here. Do you need any more information or have any further suggestions?

**Comment by dleslie** [comment]
Is it the case that allegro is split into multiple libs? That is generally the case on other platforms, and if the rest aren't included then there will be linker errors such as these.

**Comment by kalouantonis** [comment]
This is the output I get from `pkg-config --list-all | grep allegro` 

```
allegro_color-5.0      allegro_color - Allegro game programming library, colors addon
allegro_acodec-5       allegro_acodec - Allegro game programming library, audio codec addon
allegro_font-5         allegro_font - Allegro game programming library, font addon
allegro_physfs-5.0     allegro_physfs - Allegro game programming library, PhysicsFS addon
allegro_dialog-5.0     allegro_dialog - Allegro game programming library, native dialog addon
allegro_dialog-5       allegro_dialog - Allegro game programming library, native dialog addon
allegro_acodec-5.0     allegro_acodec - Allegro game programming library, audio codec addon
allegro_main-5         allegro_main - Allegro game programming library, magic main addon
allegro_image-5        allegro_image - Allegro game programming library, image I/O addon
allegro_video-5        allegro_video - Allegro game programming library, video player addon
allegro-5              allegro - Allegro game programming library
allegro_ttf-5.0        allegro_ttf - Allegro game programming library, TrueType fonts addon
allegro-5.0            allegro - Allegro game programming library
allegro_primitives-5.0 allegro_primitives - Allegro game programming library, primitives addon
allegro_primitives-5   allegro_primitives - Allegro game programming library, primitives addon
allegro_physfs-5       allegro_physfs - Allegro game programming library, PhysicsFS addon
allegro_main-5.0       allegro_main - Allegro game programming library, magic main addon
allegro_audio-5        allegro_audio - Allegro game programming library, audio addon
allegro_image-5.0      allegro_image - Allegro game programming library, image I/O addon
allegro_font-5.0       allegro_font - Allegro game programming library, font addon
allegro_audio-5.0      allegro_audio - Allegro game programming library, audio addon
allegro_memfile-5      allegro_memfile - Allegro game programming library, memory files addon
allegro_memfile-5.0    allegro_memfile - Allegro game programming library, memory files addon
allegro_ttf-5          allegro_ttf - Allegro game programming library, TrueType fonts addon
allegro_color-5        allegro_color - Allegro game programming library, colors addon
```

So, it seems like allegro is being split between multiple libraries, further confirmed by executing `ls /usr/local/lib | grep allegro`, which gives me this:

```
liballegro.5.0.11.dylib
liballegro.5.0.dylib
liballegro.5.1.12.dylib
liballegro.5.1.dylib
liballegro.dylib
liballegro_acodec.5.0.11.dylib
liballegro_acodec.5.0.dylib
liballegro_acodec.5.1.12.dylib
liballegro_acodec.5.1.dylib
liballegro_acodec.dylib
liballegro_audio.5.0.11.dylib
liballegro_audio.5.0.dylib
liballegro_audio.5.1.12.dylib
liballegro_audio.5.1.dylib
liballegro_audio.dylib
liballegro_color.5.0.11.dylib
liballegro_color.5.0.dylib
liballegro_color.5.1.12.dylib
liballegro_color.5.1.dylib
liballegro_color.dylib
liballegro_dialog.5.0.11.dylib
liballegro_dialog.5.0.dylib
liballegro_dialog.5.1.12.dylib
liballegro_dialog.5.1.dylib
liballegro_dialog.dylib
liballegro_font.5.0.11.dylib
liballegro_font.5.0.dylib
liballegro_font.5.1.12.dylib
liballegro_font.5.1.dylib
liballegro_font.dylib
liballegro_image.5.0.11.dylib
liballegro_image.5.0.dylib
liballegro_image.5.1.12.dylib
liballegro_image.5.1.dylib
liballegro_image.dylib
liballegro_main.5.0.11.dylib
liballegro_main.5.0.dylib
liballegro_main.5.1.12.dylib
liballegro_main.5.1.dylib
liballegro_main.dylib
liballegro_memfile.5.0.11.dylib
liballegro_memfile.5.0.dylib
liballegro_memfile.5.1.12.dylib
liballegro_memfile.5.1.dylib
liballegro_memfile.dylib
liballegro_physfs.5.0.11.dylib
liballegro_physfs.5.0.dylib
liballegro_physfs.5.1.12.dylib
liballegro_physfs.5.1.dylib
liballegro_physfs.dylib
liballegro_primitives.5.0.11.dylib
liballegro_primitives.5.0.dylib
liballegro_primitives.5.1.12.dylib
liballegro_primitives.5.1.dylib
liballegro_primitives.dylib
liballegro_ttf.5.0.11.dylib
liballegro_ttf.5.0.dylib
liballegro_ttf.5.1.12.dylib
liballegro_ttf.5.1.dylib
liballegro_ttf.dylib
liballegro_video.5.1.12.dylib
liballegro_video.5.1.dylib
liballegro_video.dylib
```

**Comment by dleslie** [comment]
If you don't mind, would you try adding all those to the setup and see if it links?

**Comment by kalouantonis** [comment]
Hi again, 

So after a little more digging in, I've reached another dead end. I thought that maybe removing `(include "direct3d")` from allegro.scm would provide a temporary solution.

Unfortunately, this happens:

```
allegro.c:2586:38: warning: passing 'unsigned char *' to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
C_r=C_int_to_num(&C_a,al_utf8_encode(t0,t1));
                                     ^~
/usr/local/include/allegro5/utf8.h:135:39: note: passing argument to parameter 's' here
AL_FUNC(size_t, al_utf8_encode, (char s[], int32_t c));
                                      ^
/usr/local/include/allegro5/internal/alconfig.h:172:62: note: expanded from macro 'AL_FUNC'
   #define AL_FUNC(type, name, args)               type name args
                                                             ^
allegro.c:3170:22: warning: passing 'unsigned char *' to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
al_ustr_to_buffer(t0,t1,t2);
                     ^~
/usr/local/include/allegro5/utf8.h:33:65: note: passing argument to parameter 'buffer' here
AL_FUNC(void, al_ustr_to_buffer, (const ALLEGRO_USTR *us, char *buffer, int size));
                                                                ^
/usr/local/include/allegro5/internal/alconfig.h:172:62: note: expanded from macro 'AL_FUNC'
   #define AL_FUNC(type, name, args)               type name args
                                                             ^
allegro.c:3195:61: warning: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Wpointer-sign]
C_r=C_mpointer_or_false(&C_a,(void*)al_ustr_new_from_buffer(t0,t1));
                                                            ^~
/usr/local/include/allegro5/utf8.h:29:63: note: passing argument to parameter 's' here
AL_FUNC(ALLEGRO_USTR *, al_ustr_new_from_buffer, (const char *s, size_t size));
                                                              ^
/usr/local/include/allegro5/internal/alconfig.h:172:62: note: expanded from macro 'AL_FUNC'
   #define AL_FUNC(type, name, args)               type name args
                                                             ^
allegro.c:3354:15: warning: initializing 'ALLEGRO_USTR *' (aka 'struct _al_tagbstring *') with an expression of type 'const ALLEGRO_USTR *' (aka 'const struct _al_tagbstring *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ALLEGRO_USTR *ustr = al_ref_buffer(&info, &txtp[start], end - start);
              ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
allegro.c:3377:15: warning: initializing 'ALLEGRO_USTR *' (aka 'struct _al_tagbstring *') with an expression of type 'const ALLEGRO_USTR *' (aka 'const struct _al_tagbstring *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ALLEGRO_USTR *ustr = al_ref_buffer(&info, text, length);
              ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
allegro.c:3398:15: warning: initializing 'ALLEGRO_USTR *' (aka 'struct _al_tagbstring *') with an expression of type 'const ALLEGRO_USTR *' (aka 'const struct _al_tagbstring *') discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
ALLEGRO_USTR *ustr = al_ref_buffer(&info, text, length);
              ^      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
allegro.c:3764:1: warning: implicit declaration of function '_al_put_pixel' is invalid in C99 [-Wimplicit-function-declaration]
_al_put_pixel(bmp, x, y, *c);
^
allegro.c:5198:40: warning: passing 'unsigned char *' to parameter of type 'char *' converts between pointers to integer types with different sign [-Wpointer-sign]
C_r=C_mpointer(&C_a,(void*)al_fgets(t0,t1,t2));
                                       ^~
/usr/local/include/allegro5/file.h:74:57: note: passing argument to parameter 'p' here
AL_FUNC(char*, al_fgets, (ALLEGRO_FILE *f, char * const p, size_t max));
                                                        ^
/usr/local/include/allegro5/internal/alconfig.h:172:62: note: expanded from macro 'AL_FUNC'
   #define AL_FUNC(type, name, args)               type name args
                                                             ^
allegro.c:6020:32: warning: implicit declaration of function 'al_get_allegro_image_version' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_unsigned_int_to_num(&C_a,al_get_allegro_image_version());
                               ^
allegro.c:6027:1: warning: implicit declaration of function 'al_shutdown_image_addon' is invalid in C99 [-Wimplicit-function-declaration]
al_shutdown_image_addon();
^
allegro.c:6034:15: warning: implicit declaration of function 'al_init_image_addon' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_mk_bool(al_init_image_addon());
              ^
/usr/local/Cellar/chicken/4.9.0.1/include/chicken/chicken.h:1098:38: note: expanded from macro 'C_mk_bool'
#define C_mk_bool(x)               ((x) ? C_SCHEME_TRUE : C_SCHEME_FALSE)
                                     ^
allegro.c:6230:32: warning: implicit declaration of function 'al_get_allegro_physfs_version' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_unsigned_int_to_num(&C_a,al_get_allegro_physfs_version());
                               ^
allegro.c:6237:1: warning: implicit declaration of function 'al_set_physfs_file_interface' is invalid in C99 [-Wimplicit-function-declaration]
al_set_physfs_file_interface();
^
allegro.c:6244:32: warning: implicit declaration of function 'al_get_allegro_memfile_version' is invalid in C99 [-Wimplicit-function-declaration]
C_r=C_unsigned_int_to_num(&C_a,al_get_allegro_memfile_version());
                               ^
allegro.c:6257:38: warning: implicit declaration of function 'al_open_memfile' is invalid in C99 [-Wimplicit-function-declaration]
ALLEGRO_FILE *file = (ALLEGRO_FILE *)al_open_memfile(mem, size, mode);
                                     ^
allegro.c:6257:22: warning: cast to 'ALLEGRO_FILE *' (aka 'struct ALLEGRO_FILE *') from smaller integer type 'int' [-Wint-to-pointer-cast]
ALLEGRO_FILE *file = (ALLEGRO_FILE *)al_open_memfile(mem, size, mode);
                     ^
16 warnings generated.

Error: during expansion of (import ...) - unbound variable: |\xcf\xfa\xed\xfe\x07\x00\x00\x01\x03\x00\x00\x00\x08\x00\x00\x00\x1a\x00\x00\x00\xa0\x08\x00\x00\x85\x00\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00x\x02\x00\x00__TEXT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x01\x00\x00\x00\x00\x00\x07\x00\x00\x00\x05\x00\x00\x00\x07\x00\x00\x00\x00\x00\x00\x00__text\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__TEXT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00`A\x00\x00\x00\x00\x00\x00\xb5\x05\x00\x00\x00\x00\x00\x00`A\x00\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__stubs\x00\x00\x00\x00\x00\x00\x00\x00\x00__TEXT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x16G\x00\x00\x00\x00\x00\x00T\x00\x00\x00\x00\x00\x00\x00\x16G\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x04\x00\x80\x00\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00__stub_helper\x00\x00\x00__TEXT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00lG\x00\x00\x00\x00\x00\x00\x9c\x00\x00\x00\x00\x00\x00\x00lG\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x04\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__cstring\x00\x00\x00\x00\x00\x00\x00__TEXT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08H\x00\x00\x00\x00\x00\x00\xe4\x00\x00\x00\x00\x00\x00\x00\x08H\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__const\x00\x00\x00\x00\x00\x00\x00\x00\x00__TEXT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xecH\x00\x00\x00\x00\x00\x00&\xf6\x00\x00\x00\x00\x00\x00\xecH\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__unwind_info\x00\x00\x00__TEXT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x14?\x01\x00\x00\x00\x00\x00t\x00\x00\x00\x00\x00\x00\x00\x14?\x01\x00\x02\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__eh_frame\x00\x00\x00\x00\x00\x00__TEXT\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x88?\x01\x00\x00\x00\x00\x00x\x00\x00\x00\x00\x00\x00\x00\x88?\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x19\x00\x00\x00\xd8\x01\x00\x00__DATA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x01\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00@\x01\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x03\x00\x00\x00\x05\x00\x00\x00\x00\x00\x00\x00__nl_symbol_ptr\x00__DATA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@\x01\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00@\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x0e\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__got\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__DATA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10@\x01\x00\x00\x00\x00\x000\x00\x00\x00\x00\x00\x00\x00\x10@\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__la_symbol_ptr\x00__DATA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00@@\x01\x00\x00\x00\x00\x00p\x00\x00\x00\x00\x00\x00\x00@@\x01\x00\x03\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x07\x00\x00\x00\x16\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__data\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__DATA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xb0@\x01\x00\x00\x00\x00\x00p\x00\x00\x00\x00\x00\x00\x00\xb0@\x01\x00\x04\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__bss\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00__DATA\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00|

	Call history:

	<syntax>	  (##core#begin (module allegro-glext * (import scheme chicken foreign foreigners allegro) (include "g...
	<syntax>	  (module allegro-glext * (import scheme chicken foreign foreigners allegro) (include "gl_ext_defs") (......
	<syntax>	  (##core#module allegro-glext #t (import scheme chicken foreign foreigners allegro) (include "gl_ext_...
	<syntax>	  (import scheme chicken foreign foreigners allegro)
	<syntax>	  (import scheme chicken foreign)
	<syntax>	  (##core#undefined)	<--

Error: shell command failed with nonzero exit status 256:

  '/usr/local/Cellar/chicken/4.9.0.1/bin/csc' -feature compiling-extension -setup-mode    -s -d1 allegro-glext.scm -j allegro-glext  -L/usr/local/lib -lallegro  -L/usr/local/lib -lallegro_primitives -lallegro  -L/usr/local/lib -lallegro_color -lallegro  -L/usr/local/lib -lallegro_dialog -lallegro  -L/usr/local/lib -lallegro_main -lallegro  -L/usr/local/lib -lallegro_physfs -lallegro  -L/usr/local/lib -lallegro_font -lallegro  -L/usr/local/lib -lallegro_ttf -lallegro_font -lallegro  -L/usr/local/lib -lallegro_audio -lallegro  -L/usr/local/lib -lallegro_memfile -lallegro  -L/usr/local/lib -lallegro_acodec -lallegro_audio -lallegro  -L/usr/local/lib -lallegro_image -lallegro  -O3 -C -O3 -Dimproved-64-bit-support -Dhas-allegro-primitives -Dhas-allegro-color -Dhas-allegro-dialog -Dhas-allegro-main -Dhas-allegro-physfs -Dhas-allegro-font -Dhas-allegro-ttf -Dhas-allegro-audio -Dhas-allegro-memfile -Dhas-allegro-acodec -Dhas-allegro-image


Error: shell command terminated with nonzero exit code
17920
"'/usr/local/Cellar/chicken/4.9.0.1/bin/csi' -bnq -setup-mode -e \"(require-libr...
``` 
At this point, I have no idea what's happening.

Any ideas?

**Comment by dleslie** [comment]
It looks like a memory location was erroneously bound to a symbol; or that the file being imported is using some kind of encoding that Chicken doesn't recognize.

**Comment by dleslie** [comment]
I should try and rustle up a mac.

**Comment by kalouantonis** [comment]
Digging a little deeper, I found a way past the import issues.  

I changed in `allegro.setup` from (including all the other second phase (d0) compile operations):
`(compile -s allegro-c-util.import.scm -d0 ,link-options ,compile-options
         ,@extra-defines)`
to: 
`(compile -s allegro-c-util.import.scm -d0 ,compile-options)`
which seems to get past that issue. 

I still have to comment out `(include "direct3d")`, else the linker complains.

Lastly, I get this error when linking gl-ext.

```
allegro-glext.c:4912:42: error: too few arguments to function call, expected 7, have 3
glGetTransformFeedbackVaryingEXT(t0,t1,t2);
```

Any ideas?

**Comment by dleslie** [comment]
I gladly accept pull requests!

Instead of commenting out ```(include "direct3d")``` it would be possible to use ```cond-expand``` to check for a define. 

IE, in ```allegro.setup``` there is: 
```scheme
(append extra-defines '(-Dhas-allegro-primitives))
```

Which are available to use as is done in https://github.com/dleslie/allegro-egg/blob/master/primitives.scm

```scheme
(cond-expand
 (has-allegro-primitives
  (register-feature! 'allegro-primitives)
  ...
```

The same ought to be done for Direct3D and OpenGL.

I can do this, of course. :smile:

**Comment by kalouantonis** [comment]
I asked a little on #chicken on freenode and it seems like the import issue was my local machine issue when I upgraded from chicken 4.8 to 4.9, so sorry about that. 

The Direct3D and GL stuff is still there, along with another error that just popped up.

```
/usr/local/include/allegro5/allegro_primitives.h:50:33: error: use of undeclared identifier '_ALLEGRO_PRIM_MAX_USER_ATTR'
   ALLEGRO_PRIM_MAX_USER_ATTR = _ALLEGRO_PRIM_MAX_USER_ATTR
```

I'll look at adding the cond-expand stuff and fixing the new error when I have a little more time. I'll submit the other pull request now.

**Comment by dleslie** [comment]
I've begun some work on this; hopefully I'll have the cond-expand stuff done soon.

Been a busy time for me, as of late.

**Comment by dleslie** [comment]
I've split this into issues #12 and #13.
